#!/usr/bin/env bash
docker pull docker.pkg.github.com/cqkh42/javascript-exercises/node-jasmine:latest
docker run --rm -it -v $pwd:/work docker.pkg.github.com/cqkh42/javascript-exercises/node-jasmine:latest 
